"""FORWARD TEST lifecycle, settlement and statistics.

The properties that make a recorded dataset trustworthy:

* detection freezes the hypothesis, and nothing later can revise it;
* a detected setup is not a filled setup — NO_FILL is tracked separately from
  a loss, because "untradable" and "wrong" are different failures;
* settlement is deterministic and decided by arrival, not by rule order;
* trailing tightens only, and the original invalidation survives it;
* the aggregate statistics use honest denominators;
* bullish and bearish are exact mirrors.
"""

from __future__ import annotations

from dataclasses import FrozenInstanceError, replace

import pytest

from smc.arms import settlement_variants
from smc.forward_test import (
    DEFAULT_FORWARD_TEST_CONFIG,
    ForwardTestConfig,
    SetupSnapshot,
    advance_position,
    compute_stats,
    cost_in_r,
    entry_zone,
    is_finite_plan,
    open_position,
    outcome_for,
    outcome_of,
)

T0 = 1_700_000_000.0
CFG = DEFAULT_FORWARD_TEST_CONFIG


def snapshot(direction: str = "bearish", **overrides: object) -> SetupSnapshot:
    """A bearish continuation: enter 100, stop 102, target 94 → 3R.

    The mirror (bullish) is generated by `mirrored` so symmetry is tested
    against exactly the same geometry.
    """
    reference = 100.0
    invalidation = 102.0 if direction == "bearish" else 98.0
    target = 94.0 if direction == "bearish" else 106.0
    low, high = entry_zone(direction, reference, invalidation, CFG)  # type: ignore[arg-type]
    base: dict[str, object] = dict(
        symbol="TST",
        market="perp",
        mode="SCALP",
        direction=direction,
        detected_at=T0,
        state="PULLBACK_COMPLETION",
        tier="HIGH",
        combo="structure+activity",
        families=("PARTICIPATION", "PRICE", "STRUCTURE"),
        score=72.0,
        entry_low=low,
        entry_high=high,
        reference_entry=reference,
        initial_invalidation=invalidation,
        target=target,
        target_kind="equal_lows",
        potential_rr=3.0,
        htf_bias=direction,
        htf_agreement=1.0,
        alignment="aligned",
        alignment_level="HIGH",
        structure_trend="downtrend" if direction == "bearish" else "uptrend",
        headline_event="VOLUME_ANOMALY",
        event_age_seconds=18.0,
        rvol=5.7,
        change_1m_pct=-0.9,
        change_3m_pct=-1.6,
        change_5m_pct=-2.0,
        change_15m_pct=-2.4,
        retrace_frac=0.38,
        pullback_volume_ratio=0.8,
        completion_evidence=("VOLUME_COOLED", "MICRO_CHOCH"),
        micro_choch=True,
        liquidity_target=True,
        engine_version="2.0.0",
        momentum_version="1.0.0",
        events_version="1.1.0",
        context_version="1.0.0",
        forward_test_version="1.0.0",
        config_hash="abcd1234",
        git_sha="deadbeef",
    )
    base.update(overrides)
    return SetupSnapshot(**base)  # type: ignore[arg-type]


def mirrored(price: float, pivot: float = 100.0) -> float:
    """Reflects a price around the entry so a bearish scenario becomes the
    identical bullish one."""
    return 2 * pivot - price


def run(
    setup: SetupSnapshot,
    prices: list[tuple[float, float]],
    config: ForwardTestConfig = CFG,
):
    """Feeds `(offset_seconds, price)` observations and returns the final
    position plus every event emitted."""
    position, events = open_position(setup, T0, setup.reference_entry, config)
    for offset, price in prices:
        position, more = advance_position(setup, position, price, T0 + offset, config)
        events.extend(more)
    return position, events


# ── the hypothesis is frozen ─────────────────────────────────────────────────


def test_a_snapshot_cannot_be_mutated() -> None:
    """Structural, not conventional: the type refuses."""
    setup = snapshot()
    with pytest.raises(FrozenInstanceError):
        setup.target = 90.0  # type: ignore[misc]


def test_settlement_never_revises_the_plan() -> None:
    """The plan after a full winning trade is byte-identical to the plan at
    detection — no retrospective target, no moved invalidation."""
    setup = snapshot()
    before = (setup.reference_entry, setup.initial_invalidation, setup.target, setup.potential_rr)
    position, _ = run(setup, [(30, 100.5), (60, 98.0), (90, 93.5)])
    assert position.status == "TARGET_HIT"
    assert (
        setup.reference_entry,
        setup.initial_invalidation,
        setup.target,
        setup.potential_rr,
    ) == before


def test_the_original_invalidation_survives_trailing() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.5), (60, 97.0), (90, 96.0)])
    assert position.trailing_active is True
    assert position.active_stop != setup.initial_invalidation
    assert setup.initial_invalidation == 102.0


# ── entry model ──────────────────────────────────────────────────────────────


def test_detection_is_not_a_fill() -> None:
    """The most important line in the module: a setup being detected says
    nothing about whether you could have entered it."""
    setup = snapshot()
    position, events = open_position(setup, T0, 100.0, CFG)
    assert position.status == "PENDING_ENTRY"
    assert position.filled is False
    assert [event.type for event in events] == ["SETUP_CONFIRMED"]


def test_the_entry_zone_extends_toward_the_invalidation() -> None:
    """You wait for a better price; you never chase a worse one."""
    low, high = entry_zone("bearish", 100.0, 102.0, CFG)
    assert low == pytest.approx(100.0)
    assert high > 100.0
    low, high = entry_zone("bullish", 100.0, 98.0, CFG)
    assert high == pytest.approx(100.0)
    assert low < 100.0


def test_price_reaching_the_zone_fills_the_position() -> None:
    setup = snapshot()
    position, events = run(setup, [(30, 100.4)])
    assert position.status == "ACTIVE"
    assert position.entry_price == pytest.approx(100.4)
    assert [e.type for e in events] == ["SETUP_CONFIRMED", "ENTRY_ZONE_TOUCHED", "ENTRY_FILLED"]


def test_a_setup_that_runs_away_never_fills_and_is_not_a_loss() -> None:
    setup = snapshot()
    # Price drops straight to target without ever offering the entry.
    position, events = run(
        setup, [(30, 96.0), (60, 94.0), (CFG.entry_window_seconds + 60, 93.0)]
    )
    assert position.status == "NO_FILL"
    assert position.realized_r == 0.0
    assert position.pending_mfe_pct > 0
    assert "EXPIRED" in [e.type for e in events]


def test_a_no_fill_records_whether_price_ever_reached_the_zone() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.2), (60, 100.2)])
    assert position.zone_touched_at is not None
    # …and one that never came close.
    away, _ = run(snapshot(), [(30, 96.0), (CFG.entry_window_seconds + 60, 95.0)])
    assert away.zone_touched_at is None
    assert outcome_of(snapshot(), away).touched_zone is False


# ── settlement ───────────────────────────────────────────────────────────────


def test_reaching_the_target_settles_as_a_win() -> None:
    setup = snapshot()
    position, events = run(setup, [(30, 100.4), (60, 94.0)])
    assert position.status == "TARGET_HIT"
    assert position.realized_r > 2.5
    assert position.exit_reason == "target"
    assert "TARGET_HIT" in [e.type for e in events]


def test_losing_the_invalidation_settles_as_a_loss() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.4), (60, 102.5)])
    assert position.status == "INVALIDATED"
    assert position.realized_r < 0
    assert position.exit_reason == "invalidation"


def test_a_trade_that_goes_nowhere_times_out() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.4), (CFG.max_holding_seconds + 120, 100.1)])
    assert position.status == "EXPIRED"
    assert position.exit_reason == "timeout"


def test_settlement_is_terminal() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.4), (60, 94.0)])
    settled = position
    position, events = advance_position(setup, position, 105.0, T0 + 200, CFG)
    assert position == settled
    assert events == []


def test_ordering_follows_arrival_not_rule_order() -> None:
    """Stop first then target is a loss; target first then stop is a win. The
    same two prices, opposite outcomes — decided by which arrived first."""
    stopped, _ = run(snapshot(), [(30, 100.4), (60, 102.5), (90, 94.0)])
    won, _ = run(snapshot(), [(30, 100.4), (60, 94.0), (90, 102.5)])
    assert stopped.status == "INVALIDATED"
    assert won.status == "TARGET_HIT"


# ── trailing ─────────────────────────────────────────────────────────────────


def test_trailing_activates_only_once_the_trade_is_in_profit() -> None:
    setup = snapshot()
    position, events = run(setup, [(30, 100.0), (60, 99.5)])
    assert position.trailing_active is False
    position, more = advance_position(setup, position, 97.5, T0 + 90, CFG)
    assert position.trailing_active is True
    assert "TRAIL_ACTIVATED" in [e.type for e in [*events, *more]]


def test_the_stop_only_ever_tightens() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.0), (60, 97.0), (90, 96.0)])
    tightened = position.active_stop
    # Price retraces against us: the stop must not follow it back out.
    position, _ = advance_position(setup, position, 99.0, T0 + 120, CFG)
    assert position.active_stop == tightened


def test_every_stop_move_is_preserved() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.0), (60, 97.0), (90, 96.0), (120, 95.0)])
    assert len(position.trailing_updates) >= 2
    stops = [stop for _, stop in position.trailing_updates]
    # Monotonically tightening for a bearish trade.
    assert stops == sorted(stops, reverse=True)


def test_a_trailed_exit_is_labelled_as_one() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.0), (60, 96.0), (90, 99.5)])
    assert position.status == "INVALIDATED"
    assert position.exit_reason == "trailing_stop"
    # Trailed out above breakeven: a small win, not the structural loss.
    assert position.realized_r > 0


def test_trailing_can_be_switched_off_entirely() -> None:
    config = replace(CFG, trailing_mode="NONE")
    setup = snapshot()
    position, _ = run(setup, [(30, 100.0), (60, 96.0), (90, 95.0)], config)
    assert position.trailing_active is False
    assert position.active_stop == setup.initial_invalidation


# ── excursions ───────────────────────────────────────────────────────────────


def test_excursions_are_signed_toward_the_thesis() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.4), (60, 98.0), (90, 101.0)])
    assert position.mfe_pct > 0
    assert position.mae_pct < 0
    assert position.mfe_r > 0
    assert position.mae_r < 0


def test_excursions_are_measured_from_the_fill_not_the_reference() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.4), (60, 100.4)])
    assert position.mfe_pct == pytest.approx(0.0)


# ── symmetry ─────────────────────────────────────────────────────────────────


def test_bullish_and_bearish_are_exact_mirrors() -> None:
    bear = snapshot("bearish")
    bull = snapshot("bullish")
    path = [(30, 100.4), (60, 98.0), (90, 94.0)]
    bear_position, bear_events = run(bear, path)
    bull_position, bull_events = run(bull, [(t, mirrored(p)) for t, p in path])

    assert bear_position.status == bull_position.status == "TARGET_HIT"
    # Gross R mirrors exactly; net R only to within the cost of the price
    # difference, because a fee is a share of price and mirroring around 100
    # fills the two sides at 100.4 and 99.6.
    assert bear_position.gross_r == pytest.approx(bull_position.gross_r)
    assert bear_position.realized_r == pytest.approx(bull_position.realized_r, rel=1e-3)
    assert bear_position.mfe_r == pytest.approx(bull_position.mfe_r)
    assert [e.type for e in bear_events] == [e.type for e in bull_events]


def test_mirrored_losses_match_too() -> None:
    path = [(30, 100.4), (60, 102.5)]
    bear, _ = run(snapshot("bearish"), path)
    bull, _ = run(snapshot("bullish"), [(t, mirrored(p)) for t, p in path])
    assert bear.status == bull.status == "INVALIDATED"
    assert bear.gross_r == pytest.approx(bull.gross_r)
    assert bear.realized_r == pytest.approx(bull.realized_r, rel=1e-3)


# ── determinism ──────────────────────────────────────────────────────────────


def test_the_same_observations_always_produce_the_same_record() -> None:
    path = [(30, 100.4), (60, 98.0), (90, 96.0), (120, 94.0)]
    first, first_events = run(snapshot(), path)
    second, second_events = run(snapshot(), path)
    assert first == second
    assert [(e.type, e.ts, e.price) for e in first_events] == [
        (e.type, e.ts, e.price) for e in second_events
    ]


def test_a_degenerate_plan_is_rejected_before_it_is_recorded() -> None:
    assert is_finite_plan(100.0, 102.0, 94.0) is True
    assert is_finite_plan(100.0, 100.0, 94.0) is False
    assert is_finite_plan(100.0, 102.0, 100.0) is False
    assert is_finite_plan(0.0, 102.0, 94.0) is False
    assert is_finite_plan(float("inf"), 102.0, 94.0) is False


# ── aggregate statistics ─────────────────────────────────────────────────────


def rows(*items: tuple[str, float, float, float]) -> list[tuple[str, float, float, float]]:
    return list(items)


def test_win_rate_counts_fills_and_fill_rate_counts_setups() -> None:
    """Mixing these denominators is the easiest way to make an untradable
    strategy look tradable."""
    stats = compute_stats(
        rows(
            ("TARGET_HIT", 3.0, 3.0, -0.2),
            ("INVALIDATED", -1.0, 0.4, -1.0),
            ("NO_FILL", 0.0, 0.0, 0.0),
            ("NO_FILL", 0.0, 0.0, 0.0),
        )
    )
    assert stats.total == 4
    assert stats.filled == 2
    assert stats.fill_rate == pytest.approx(0.5)
    assert stats.win_rate == pytest.approx(0.5)
    assert stats.no_fill_rate == pytest.approx(0.5)


def test_open_setups_are_excluded_from_settled_rates() -> None:
    stats = compute_stats(rows(("PENDING_ENTRY", 0.0, 0.0, 0.0), ("TARGET_HIT", 2.0, 2.0, 0.0)))
    assert stats.open == 1
    assert stats.fill_rate == pytest.approx(1.0)
    assert stats.win_rate == pytest.approx(1.0)


def test_expectancy_is_per_recorded_setup_not_per_fill() -> None:
    """A setup you could not enter still consumed the opportunity."""
    stats = compute_stats(rows(("TARGET_HIT", 3.0, 3.0, 0.0), ("NO_FILL", 0.0, 0.0, 0.0)))
    assert stats.average_r == pytest.approx(3.0)
    assert stats.expectancy == pytest.approx(1.5)


def test_profit_factor_and_drawdown() -> None:
    stats = compute_stats(
        rows(
            ("TARGET_HIT", 3.0, 3.0, -0.3),
            ("INVALIDATED", -1.0, 0.2, -1.0),
            ("INVALIDATED", -1.0, 0.1, -1.0),
            ("TARGET_HIT", 2.0, 2.0, -0.4),
        )
    )
    assert stats.profit_factor == pytest.approx(2.5)
    assert stats.total_r == pytest.approx(3.0)
    assert stats.max_drawdown_r == pytest.approx(-2.0)


def test_empty_statistics_are_zeroed_not_undefined() -> None:
    stats = compute_stats([])
    assert stats.total == 0
    assert stats.win_rate == 0.0
    assert stats.profit_factor == 0.0
    assert stats.expectancy == 0.0


def test_the_outcome_view_reports_the_timings() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.4), (120, 94.0)])
    outcome = outcome_of(setup, position)
    assert outcome.time_to_entry == pytest.approx(30.0)
    assert outcome.time_in_trade == pytest.approx(90.0)
    assert outcome.time_to_settle == pytest.approx(120.0)
    assert outcome.target_reached is True


# ── costs ────────────────────────────────────────────────────────────────────


def test_costs_are_deducted_from_the_realized_result() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.4), (60, 94.0)])
    assert position.status == "TARGET_HIT"
    assert position.gross_r > position.realized_r
    assert position.cost_r > 0
    assert position.realized_r == pytest.approx(position.gross_r - position.cost_r, abs=2e-4)


def test_a_tighter_stop_pays_a_larger_share_of_its_risk_in_costs() -> None:
    """The whole reason a scalp and a swing cannot be compared on gross R: the
    same fee is a much bigger fraction of a narrow stop."""
    tight = snapshot(initial_invalidation=100.5)  # 0.5% stop
    wide = snapshot(initial_invalidation=105.0)  # 5% stop
    assert cost_in_r(tight, 100.0, CFG) > 5 * cost_in_r(wide, 100.0, CFG)


def test_the_entry_leg_is_priced_as_the_resting_order_it_is() -> None:
    """`advance_position` fills the entry only when price trades into the zone
    and records NO_FILL when it never does — the behaviour of an order that
    waits to be hit. It cannot also be charged for crossing the spread."""
    assert CFG.entry_leg_cost_pct == CFG.maker_leg_cost_pct
    assert CFG.entry_leg_cost_pct < CFG.taker_leg_cost_pct


def test_a_target_exit_makes_and_every_other_exit_takes() -> None:
    assert CFG.exit_leg_cost_pct("target") == CFG.maker_leg_cost_pct
    for reason in ("invalidation", "trailing_stop", "timeout"):
        assert CFG.exit_leg_cost_pct(reason) == CFG.taker_leg_cost_pct


def test_an_unknown_exit_reason_is_charged_as_a_taker() -> None:
    """A position still open may yet stop out. Assuming otherwise would
    flatter every unsettled trade on the board."""
    assert CFG.exit_leg_cost_pct("") == CFG.taker_leg_cost_pct
    assert CFG.exit_leg_cost_pct("something_new") == CFG.taker_leg_cost_pct
    setup = snapshot()
    assert cost_in_r(setup, 100.0, CFG) == cost_in_r(setup, 100.0, CFG, "invalidation")


def test_a_target_hit_costs_less_than_a_stop_out_on_the_same_geometry() -> None:
    setup = snapshot()
    assert cost_in_r(setup, 100.0, CFG, "target") < cost_in_r(setup, 100.0, CFG, "invalidation")


def test_a_settled_record_is_charged_by_what_actually_closed_it() -> None:
    setup = snapshot()
    hit, _ = run(setup, [(30, 100.0), (60, 90.0)])
    stopped, _ = run(setup, [(30, 100.0), (60, 102.5)])
    assert hit.exit_reason == "target" and stopped.exit_reason == "invalidation"
    assert hit.cost_r == pytest.approx(cost_in_r(setup, hit.entry_price or 0.0, CFG, "target"))
    assert stopped.cost_r > hit.cost_r


def test_a_maker_leg_may_never_be_configured_dearer_than_a_taker_leg() -> None:
    with pytest.raises(ValueError):
        replace(CFG, maker_fee_pct=0.9)


def test_costs_can_turn_a_marginal_winner_into_a_loser() -> None:
    cheap = replace(CFG, taker_fee_pct=0.0, slippage_pct=0.0, maker_fee_pct=0.0, maker_slippage_pct=0.0)
    expensive = replace(
        CFG, taker_fee_pct=0.4, slippage_pct=0.2, maker_fee_pct=0.4, maker_slippage_pct=0.2
    )
    setup = snapshot()
    # Runs to 1.5R, then trails out just under half an R of gross profit.
    path = [(30, 100.0), (60, 97.0), (90, 99.05)]
    free, _ = run(setup, path, cheap)
    costly, _ = run(setup, path, expensive)
    assert free.realized_r > 0
    assert costly.realized_r < 0
    assert free.gross_r == pytest.approx(costly.gross_r)


def test_a_no_fill_pays_nothing() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 96.0), (CFG.entry_window_seconds + 60, 95.0)])
    assert position.status == "NO_FILL"
    assert position.cost_r == 0.0
    assert position.realized_r == 0.0


def test_zero_cost_reproduces_the_gross_result() -> None:
    free = replace(CFG, taker_fee_pct=0.0, slippage_pct=0.0, maker_fee_pct=0.0, maker_slippage_pct=0.0)
    position, _ = run(snapshot(), [(30, 100.4), (60, 94.0)], free)
    assert position.realized_r == pytest.approx(position.gross_r)


def test_negative_costs_are_rejected() -> None:
    with pytest.raises(ValueError, match="costs cannot be negative"):
        ForwardTestConfig(taker_fee_pct=-0.1)


# ── exit-rule variants ───────────────────────────────────────────────────────
#
# These exercise the settlement engine's response to a trailing config, so they
# build the configs they need with `replace` rather than reading them out of
# `smc.arms`. They used to index into `settlement_variants()`, which coupled
# the engine's own tests to which arms happened to be registered — retiring the
# exit axis on 2026-08-18 broke all three without anything in the engine
# changing. The engine knows nothing about axes; neither should its tests.

NO_TRAIL = replace(CFG, trailing_mode="NONE")
WIDE_TRAIL = replace(CFG, trailing_activation_r=1.5, trailing_distance_r=1.5)


def test_the_same_setup_and_prices_settle_differently_under_different_exit_rules() -> None:
    """The controlled experiment the whole variant machinery exists for:
    identical detection and entry, different exit rules, settled forward
    together against one price path."""
    setup = snapshot()
    path = [(30, 100.0), (60, 97.0), (90, 99.05), (120, 94.0)]
    primary, _ = run(setup, path, CFG)
    held, _ = run(setup, path, NO_TRAIL)

    # The primary trails out early; holding the structural stop reaches target.
    assert primary.status == "INVALIDATED"
    assert primary.exit_reason == "trailing_stop"
    assert held.status == "TARGET_HIT"
    assert held.realized_r > primary.realized_r


def test_every_registered_variant_settles_independently_on_one_path() -> None:
    """Whatever the registry currently holds, each variant gets its own
    position off the same frozen snapshot and the same prices. Asserted over
    the registry as it is, so it keeps holding as arms come and go."""
    setup = snapshot()
    path = [(30, 100.0), (60, 97.0), (90, 99.05), (120, 94.0)]
    variants = settlement_variants(CFG)
    assert variants, "the registry should always offer at least one variant"
    results = {v.name: run(setup, path, v.config)[0] for v in variants}
    assert len(results) == len(variants)
    for position in results.values():
        assert position.entered_at is not None


def test_a_looser_trail_survives_a_retracement_the_tight_one_does_not() -> None:
    setup = snapshot()
    path = [(30, 100.0), (60, 97.0), (90, 99.05)]
    tight, _ = run(setup, path, CFG)
    wide, _ = run(setup, path, WIDE_TRAIL)
    assert tight.status == "INVALIDATED"
    assert wide.status == "ACTIVE"


def test_a_variant_that_gives_back_more_is_recorded_as_such() -> None:
    """Loosening is not free — the same rule that saves a winner also holds a
    reversal longer. Both directions have to be measurable."""
    setup = snapshot()
    # Runs to 1.2R, retraces past the *trailed* stop but not the structural
    # one, then reverses through it. The tight rule banks a scratch; the loose
    # one is still in the trade and takes the full loss.
    path = [(30, 100.0), (60, 97.6), (90, 99.7), (120, 102.5)]
    tight, _ = run(setup, path, CFG)
    loose, _ = run(setup, path, NO_TRAIL)
    assert tight.realized_r > loose.realized_r
    assert loose.exit_reason == "invalidation"


def test_the_variant_outcome_is_flat_and_complete() -> None:
    setup = snapshot()
    position, _ = run(setup, [(30, 100.4), (60, 94.0)])
    outcome = outcome_for("no_trail", position)
    assert outcome.name == "no_trail"
    assert outcome.status == "TARGET_HIT"
    assert outcome.is_settled is True
    assert outcome.gross_r > outcome.realized_r
    assert outcome.settled_at is not None


# ─────────────────────────────────────────────────────────────────────────────
# The fill model: the observation decides whether, the order decides where
# ─────────────────────────────────────────────────────────────────────────────


def test_a_stop_exit_fills_at_the_stop_not_at_the_price_that_revealed_it() -> None:
    """Generation 4's dominant leak: 13.9R of sampling-rate slippage.

    Entry 100, stop 102, so risk is 2. The poll that discovers the breach
    prints 104 — a full extra R past the stop. A resting stop order was hit at
    102 and the trade is worth -1R gross, not -2R.
    """
    setup = snapshot()
    position, _ = run(setup, [(30, 100.0), (60, 104.0)])
    assert position.status == "INVALIDATED"
    assert position.exit_price == pytest.approx(102.0)
    assert position.gross_r == pytest.approx(-1.0)


def test_a_target_exit_fills_at_the_target_not_beyond_it() -> None:
    """The same correction, and it costs us — which is how we know it is not
    an outcome tune. Generation 4 collected 2.97R of favourable overshoot."""
    setup = snapshot()
    position, _ = run(setup, [(30, 100.0), (60, 90.0)])
    assert position.status == "TARGET_HIT"
    assert position.exit_price == pytest.approx(94.0)
    assert position.gross_r == pytest.approx(3.0)


def test_the_observed_price_is_still_recorded_on_the_event() -> None:
    """Correcting the fill must not hide what was actually seen."""
    setup = snapshot()
    _, events = run(setup, [(30, 100.0), (60, 104.0)])
    invalidated = [e for e in events if e.type == "INVALIDATED"][-1]
    assert invalidated.price == pytest.approx(104.0)
    assert invalidated.detail["observed"] == pytest.approx(104.0)
    assert invalidated.detail["fill"] == pytest.approx(102.0)


def test_a_trailed_exit_fills_at_the_trailed_stop() -> None:
    """The stop in force is the one that fills, not the initial one."""
    setup = snapshot()
    position, _ = run(setup, [(30, 100.0), (60, 98.0), (90, 101.0)])
    assert position.status == "INVALIDATED"
    assert position.exit_reason == "trailing_stop"
    assert position.exit_price == pytest.approx(position.active_stop)
    # Reaching exactly 1R trails to breakeven (activation 1R, distance 1R), so
    # the scratch is gross-flat and loses only the round trip.
    assert position.gross_r == pytest.approx(0.0)
    assert position.active_stop == pytest.approx(100.0)
    assert position.realized_r < 0


def test_the_timeout_still_fills_at_the_market() -> None:
    """A hold that runs out has no resting order to fill against — it is
    closed at whatever is there, and that price is genuine."""
    setup = snapshot()
    position, _ = run(setup, [(30, 100.0), (CFG.max_holding_seconds + 120, 99.3)])
    assert position.status == "EXPIRED"
    assert position.exit_price == pytest.approx(99.3)


def test_fills_are_mirrored() -> None:
    bear, _ = run(snapshot("bearish"), [(30, 100.0), (60, 104.0)])
    bull, _ = run(snapshot("bullish"), [(30, 100.0), (60, 96.0)])
    assert bear.gross_r == pytest.approx(bull.gross_r)
