/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TechnicalRouteImport } from './routes/technical'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RotationRouteImport } from './routes/rotation'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegimeRouteImport } from './routes/regime'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenSymbolRouteImport } from './routes/token.$symbol'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiUniverseRouteImport } from './routes/api/universe'
import { Route as ApiTradesRouteImport } from './routes/api/trades'
import { Route as ApiTrackTokenRouteImport } from './routes/api/track-token'
import { Route as ApiTokenEventsRouteImport } from './routes/api/token-events'
import { Route as ApiSignalsRouteImport } from './routes/api/signals'
import { Route as ApiScorecardRouteImport } from './routes/api/scorecard'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as ApiOpportunitiesRouteImport } from './routes/api/opportunities'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiKlinesRouteImport } from './routes/api/klines'
import { Route as ApiForwardTestRouteImport } from './routes/api/forward-test'
import { Route as ApiExternalContextRouteImport } from './routes/api/external-context'
import { Route as ApiEconomicEventsRouteImport } from './routes/api/economic-events'
import { Route as ApiDerivativesRouteImport } from './routes/api/derivatives'
import { Route as ApiDecisionsRouteImport } from './routes/api/decisions'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiTradesIdRouteImport } from './routes/api/trades.$id'
import { Route as ApiReviewForensicsRouteImport } from './routes/api/review.forensics'
import { Route as ApiReviewAnalyticsRouteImport } from './routes/api/review.analytics'
import { Route as ApiReviewIdRouteImport } from './routes/api/review.$id'
import { Route as ApiPositionsStreamRouteImport } from './routes/api/positions.stream'
import { Route as ApiExecutionSkipCheckRouteImport } from './routes/api/execution.skip-check'
import { Route as ApiExecutionPermitRouteImport } from './routes/api/execution.permit'
import { Route as ApiExecutionExecutionsRouteImport } from './routes/api/execution.executions'
import { Route as ApiExecutionExecuteRouteImport } from './routes/api/execution.execute'
import { Route as ApiExecutionConstitutionRouteImport } from './routes/api/execution.constitution'
import { Route as ApiBinanceReviewTradesRouteImport } from './routes/api/binance-review.trades'
import { Route as ApiBinanceReviewSyncRouteImport } from './routes/api/binance-review.sync'
import { Route as ApiBinanceReviewApiKeyRouteImport } from './routes/api/binance-review.api-key'
import { Route as ApiAuthTelegramRouteImport } from './routes/api/auth.telegram'
import { Route as ApiAiDeskAnalyzeTradesRouteImport } from './routes/api/ai-desk.analyze-trades'
import { Route as ApiReviewForensicsTradeIdRouteImport } from './routes/api/review.forensics.$tradeId'
import { Route as ApiExecutionPermitIdRouteImport } from './routes/api/execution.permit.$id'
import { Route as ApiDecisionsIdActionRouteImport } from './routes/api/decisions.$id.action'
import { Route as ApiAlertsIdReadRouteImport } from './routes/api/alerts.$id.read'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RotationRoute = RotationRouteImport.update({
  id: '/rotation',
  path: '/rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimeRoute = RegimeRouteImport.update({
  id: '/regime',
  path: '/regime',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenSymbolRoute = TokenSymbolRouteImport.update({
  id: '/token/$symbol',
  path: '/token/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUniverseRoute = ApiUniverseRouteImport.update({
  id: '/api/universe',
  path: '/api/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesRoute = ApiTradesRouteImport.update({
  id: '/api/trades',
  path: '/api/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackTokenRoute = ApiTrackTokenRouteImport.update({
  id: '/api/track-token',
  path: '/api/track-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenEventsRoute = ApiTokenEventsRouteImport.update({
  id: '/api/token-events',
  path: '/api/token-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsRoute = ApiSignalsRouteImport.update({
  id: '/api/signals',
  path: '/api/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScorecardRoute = ApiScorecardRouteImport.update({
  id: '/api/scorecard',
  path: '/api/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpportunitiesRoute = ApiOpportunitiesRouteImport.update({
  id: '/api/opportunities',
  path: '/api/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKlinesRoute = ApiKlinesRouteImport.update({
  id: '/api/klines',
  path: '/api/klines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForwardTestRoute = ApiForwardTestRouteImport.update({
  id: '/api/forward-test',
  path: '/api/forward-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalContextRoute = ApiExternalContextRouteImport.update({
  id: '/api/external-context',
  path: '/api/external-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEconomicEventsRoute = ApiEconomicEventsRouteImport.update({
  id: '/api/economic-events',
  path: '/api/economic-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDerivativesRoute = ApiDerivativesRouteImport.update({
  id: '/api/derivatives',
  path: '/api/derivatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecisionsRoute = ApiDecisionsRouteImport.update({
  id: '/api/decisions',
  path: '/api/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesIdRoute = ApiTradesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTradesRoute,
} as any)
const ApiReviewForensicsRoute = ApiReviewForensicsRouteImport.update({
  id: '/api/review/forensics',
  path: '/api/review/forensics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewAnalyticsRoute = ApiReviewAnalyticsRouteImport.update({
  id: '/api/review/analytics',
  path: '/api/review/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewIdRoute = ApiReviewIdRouteImport.update({
  id: '/api/review/$id',
  path: '/api/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPositionsStreamRoute = ApiPositionsStreamRouteImport.update({
  id: '/api/positions/stream',
  path: '/api/positions/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionSkipCheckRoute = ApiExecutionSkipCheckRouteImport.update({
  id: '/api/execution/skip-check',
  path: '/api/execution/skip-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionPermitRoute = ApiExecutionPermitRouteImport.update({
  id: '/api/execution/permit',
  path: '/api/execution/permit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionExecutionsRoute = ApiExecutionExecutionsRouteImport.update({
  id: '/api/execution/executions',
  path: '/api/execution/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionExecuteRoute = ApiExecutionExecuteRouteImport.update({
  id: '/api/execution/execute',
  path: '/api/execution/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionConstitutionRoute =
  ApiExecutionConstitutionRouteImport.update({
    id: '/api/execution/constitution',
    path: '/api/execution/constitution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBinanceReviewTradesRoute = ApiBinanceReviewTradesRouteImport.update({
  id: '/api/binance-review/trades',
  path: '/api/binance-review/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceReviewSyncRoute = ApiBinanceReviewSyncRouteImport.update({
  id: '/api/binance-review/sync',
  path: '/api/binance-review/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceReviewApiKeyRoute = ApiBinanceReviewApiKeyRouteImport.update({
  id: '/api/binance-review/api-key',
  path: '/api/binance-review/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTelegramRoute = ApiAuthTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAiDeskAnalyzeTradesRoute = ApiAiDeskAnalyzeTradesRouteImport.update({
  id: '/api/ai-desk/analyze-trades',
  path: '/api/ai-desk/analyze-trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewForensicsTradeIdRoute =
  ApiReviewForensicsTradeIdRouteImport.update({
    id: '/$tradeId',
    path: '/$tradeId',
    getParentRoute: () => ApiReviewForensicsRoute,
  } as any)
const ApiExecutionPermitIdRoute = ApiExecutionPermitIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExecutionPermitRoute,
} as any)
const ApiDecisionsIdActionRoute = ApiDecisionsIdActionRouteImport.update({
  id: '/$id/action',
  path: '/$id/action',
  getParentRoute: () => ApiDecisionsRoute,
} as any)
const ApiAlertsIdReadRoute = ApiAlertsIdReadRouteImport.update({
  id: '/$id/read',
  path: '/$id/read',
  getParentRoute: () => ApiAlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/ideas': typeof IdeasRoute
  '/journal': typeof JournalRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/review': typeof ReviewRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/decisions': typeof ApiDecisionsRouteWithChildren
  '/api/derivatives': typeof ApiDerivativesRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/opportunities': typeof ApiOpportunitiesRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/scorecard': typeof ApiScorecardRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/universe': typeof ApiUniverseRoute
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/ai-desk/analyze-trades': typeof ApiAiDeskAnalyzeTradesRoute
  '/api/auth/telegram': typeof ApiAuthTelegramRoute
  '/api/binance-review/api-key': typeof ApiBinanceReviewApiKeyRoute
  '/api/binance-review/sync': typeof ApiBinanceReviewSyncRoute
  '/api/binance-review/trades': typeof ApiBinanceReviewTradesRoute
  '/api/execution/constitution': typeof ApiExecutionConstitutionRoute
  '/api/execution/execute': typeof ApiExecutionExecuteRoute
  '/api/execution/executions': typeof ApiExecutionExecutionsRoute
  '/api/execution/permit': typeof ApiExecutionPermitRouteWithChildren
  '/api/execution/skip-check': typeof ApiExecutionSkipCheckRoute
  '/api/positions/stream': typeof ApiPositionsStreamRoute
  '/api/review/$id': typeof ApiReviewIdRoute
  '/api/review/analytics': typeof ApiReviewAnalyticsRoute
  '/api/review/forensics': typeof ApiReviewForensicsRouteWithChildren
  '/api/trades/$id': typeof ApiTradesIdRoute
  '/api/alerts/$id/read': typeof ApiAlertsIdReadRoute
  '/api/decisions/$id/action': typeof ApiDecisionsIdActionRoute
  '/api/execution/permit/$id': typeof ApiExecutionPermitIdRoute
  '/api/review/forensics/$tradeId': typeof ApiReviewForensicsTradeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/ideas': typeof IdeasRoute
  '/journal': typeof JournalRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/review': typeof ReviewRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/decisions': typeof ApiDecisionsRouteWithChildren
  '/api/derivatives': typeof ApiDerivativesRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/opportunities': typeof ApiOpportunitiesRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/scorecard': typeof ApiScorecardRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/universe': typeof ApiUniverseRoute
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/ai-desk/analyze-trades': typeof ApiAiDeskAnalyzeTradesRoute
  '/api/auth/telegram': typeof ApiAuthTelegramRoute
  '/api/binance-review/api-key': typeof ApiBinanceReviewApiKeyRoute
  '/api/binance-review/sync': typeof ApiBinanceReviewSyncRoute
  '/api/binance-review/trades': typeof ApiBinanceReviewTradesRoute
  '/api/execution/constitution': typeof ApiExecutionConstitutionRoute
  '/api/execution/execute': typeof ApiExecutionExecuteRoute
  '/api/execution/executions': typeof ApiExecutionExecutionsRoute
  '/api/execution/permit': typeof ApiExecutionPermitRouteWithChildren
  '/api/execution/skip-check': typeof ApiExecutionSkipCheckRoute
  '/api/positions/stream': typeof ApiPositionsStreamRoute
  '/api/review/$id': typeof ApiReviewIdRoute
  '/api/review/analytics': typeof ApiReviewAnalyticsRoute
  '/api/review/forensics': typeof ApiReviewForensicsRouteWithChildren
  '/api/trades/$id': typeof ApiTradesIdRoute
  '/api/alerts/$id/read': typeof ApiAlertsIdReadRoute
  '/api/decisions/$id/action': typeof ApiDecisionsIdActionRoute
  '/api/execution/permit/$id': typeof ApiExecutionPermitIdRoute
  '/api/review/forensics/$tradeId': typeof ApiReviewForensicsTradeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/ideas': typeof IdeasRoute
  '/journal': typeof JournalRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/review': typeof ReviewRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/decisions': typeof ApiDecisionsRouteWithChildren
  '/api/derivatives': typeof ApiDerivativesRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/opportunities': typeof ApiOpportunitiesRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/scorecard': typeof ApiScorecardRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/universe': typeof ApiUniverseRoute
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/ai-desk/analyze-trades': typeof ApiAiDeskAnalyzeTradesRoute
  '/api/auth/telegram': typeof ApiAuthTelegramRoute
  '/api/binance-review/api-key': typeof ApiBinanceReviewApiKeyRoute
  '/api/binance-review/sync': typeof ApiBinanceReviewSyncRoute
  '/api/binance-review/trades': typeof ApiBinanceReviewTradesRoute
  '/api/execution/constitution': typeof ApiExecutionConstitutionRoute
  '/api/execution/execute': typeof ApiExecutionExecuteRoute
  '/api/execution/executions': typeof ApiExecutionExecutionsRoute
  '/api/execution/permit': typeof ApiExecutionPermitRouteWithChildren
  '/api/execution/skip-check': typeof ApiExecutionSkipCheckRoute
  '/api/positions/stream': typeof ApiPositionsStreamRoute
  '/api/review/$id': typeof ApiReviewIdRoute
  '/api/review/analytics': typeof ApiReviewAnalyticsRoute
  '/api/review/forensics': typeof ApiReviewForensicsRouteWithChildren
  '/api/trades/$id': typeof ApiTradesIdRoute
  '/api/alerts/$id/read': typeof ApiAlertsIdReadRoute
  '/api/decisions/$id/action': typeof ApiDecisionsIdActionRoute
  '/api/execution/permit/$id': typeof ApiExecutionPermitIdRoute
  '/api/review/forensics/$tradeId': typeof ApiReviewForensicsTradeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/book'
    | '/ideas'
    | '/journal'
    | '/lab'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/review'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/api/alerts'
    | '/api/auth'
    | '/api/decisions'
    | '/api/derivatives'
    | '/api/economic-events'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/notifications'
    | '/api/opportunities'
    | '/api/preferences'
    | '/api/scorecard'
    | '/api/signals'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/universe'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/ai-desk/analyze-trades'
    | '/api/auth/telegram'
    | '/api/binance-review/api-key'
    | '/api/binance-review/sync'
    | '/api/binance-review/trades'
    | '/api/execution/constitution'
    | '/api/execution/execute'
    | '/api/execution/executions'
    | '/api/execution/permit'
    | '/api/execution/skip-check'
    | '/api/positions/stream'
    | '/api/review/$id'
    | '/api/review/analytics'
    | '/api/review/forensics'
    | '/api/trades/$id'
    | '/api/alerts/$id/read'
    | '/api/decisions/$id/action'
    | '/api/execution/permit/$id'
    | '/api/review/forensics/$tradeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/book'
    | '/ideas'
    | '/journal'
    | '/lab'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/review'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/api/alerts'
    | '/api/auth'
    | '/api/decisions'
    | '/api/derivatives'
    | '/api/economic-events'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/notifications'
    | '/api/opportunities'
    | '/api/preferences'
    | '/api/scorecard'
    | '/api/signals'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/universe'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/ai-desk/analyze-trades'
    | '/api/auth/telegram'
    | '/api/binance-review/api-key'
    | '/api/binance-review/sync'
    | '/api/binance-review/trades'
    | '/api/execution/constitution'
    | '/api/execution/execute'
    | '/api/execution/executions'
    | '/api/execution/permit'
    | '/api/execution/skip-check'
    | '/api/positions/stream'
    | '/api/review/$id'
    | '/api/review/analytics'
    | '/api/review/forensics'
    | '/api/trades/$id'
    | '/api/alerts/$id/read'
    | '/api/decisions/$id/action'
    | '/api/execution/permit/$id'
    | '/api/review/forensics/$tradeId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/book'
    | '/ideas'
    | '/journal'
    | '/lab'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/review'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/api/alerts'
    | '/api/auth'
    | '/api/decisions'
    | '/api/derivatives'
    | '/api/economic-events'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/notifications'
    | '/api/opportunities'
    | '/api/preferences'
    | '/api/scorecard'
    | '/api/signals'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/universe'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/ai-desk/analyze-trades'
    | '/api/auth/telegram'
    | '/api/binance-review/api-key'
    | '/api/binance-review/sync'
    | '/api/binance-review/trades'
    | '/api/execution/constitution'
    | '/api/execution/execute'
    | '/api/execution/executions'
    | '/api/execution/permit'
    | '/api/execution/skip-check'
    | '/api/positions/stream'
    | '/api/review/$id'
    | '/api/review/analytics'
    | '/api/review/forensics'
    | '/api/trades/$id'
    | '/api/alerts/$id/read'
    | '/api/decisions/$id/action'
    | '/api/execution/permit/$id'
    | '/api/review/forensics/$tradeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BookRoute: typeof BookRoute
  IdeasRoute: typeof IdeasRoute
  JournalRoute: typeof JournalRoute
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  RankingsRoute: typeof RankingsRoute
  RegimeRoute: typeof RegimeRoute
  ReviewRoute: typeof ReviewRoute
  RotationRoute: typeof RotationRoute
  SettingsRoute: typeof SettingsRoute
  TechnicalRoute: typeof TechnicalRoute
  TrackerRoute: typeof TrackerRoute
  TradesRoute: typeof TradesRoute
  ApiAlertsRoute: typeof ApiAlertsRouteWithChildren
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiDecisionsRoute: typeof ApiDecisionsRouteWithChildren
  ApiDerivativesRoute: typeof ApiDerivativesRoute
  ApiEconomicEventsRoute: typeof ApiEconomicEventsRoute
  ApiExternalContextRoute: typeof ApiExternalContextRoute
  ApiForwardTestRoute: typeof ApiForwardTestRoute
  ApiKlinesRoute: typeof ApiKlinesRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiOpportunitiesRoute: typeof ApiOpportunitiesRoute
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  ApiScorecardRoute: typeof ApiScorecardRoute
  ApiSignalsRoute: typeof ApiSignalsRoute
  ApiTokenEventsRoute: typeof ApiTokenEventsRoute
  ApiTrackTokenRoute: typeof ApiTrackTokenRoute
  ApiTradesRoute: typeof ApiTradesRouteWithChildren
  ApiUniverseRoute: typeof ApiUniverseRoute
  ApiWatchlistRoute: typeof ApiWatchlistRoute
  TokenSymbolRoute: typeof TokenSymbolRoute
  ApiAiDeskAnalyzeTradesRoute: typeof ApiAiDeskAnalyzeTradesRoute
  ApiBinanceReviewApiKeyRoute: typeof ApiBinanceReviewApiKeyRoute
  ApiBinanceReviewSyncRoute: typeof ApiBinanceReviewSyncRoute
  ApiBinanceReviewTradesRoute: typeof ApiBinanceReviewTradesRoute
  ApiExecutionConstitutionRoute: typeof ApiExecutionConstitutionRoute
  ApiExecutionExecuteRoute: typeof ApiExecutionExecuteRoute
  ApiExecutionExecutionsRoute: typeof ApiExecutionExecutionsRoute
  ApiExecutionPermitRoute: typeof ApiExecutionPermitRouteWithChildren
  ApiExecutionSkipCheckRoute: typeof ApiExecutionSkipCheckRoute
  ApiPositionsStreamRoute: typeof ApiPositionsStreamRoute
  ApiReviewIdRoute: typeof ApiReviewIdRoute
  ApiReviewAnalyticsRoute: typeof ApiReviewAnalyticsRoute
  ApiReviewForensicsRoute: typeof ApiReviewForensicsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotation': {
      id: '/rotation'
      path: '/rotation'
      fullPath: '/rotation'
      preLoaderRoute: typeof RotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regime': {
      id: '/regime'
      path: '/regime'
      fullPath: '/regime'
      preLoaderRoute: typeof RegimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$symbol': {
      id: '/token/$symbol'
      path: '/token/$symbol'
      fullPath: '/token/$symbol'
      preLoaderRoute: typeof TokenSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/universe': {
      id: '/api/universe'
      path: '/api/universe'
      fullPath: '/api/universe'
      preLoaderRoute: typeof ApiUniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades': {
      id: '/api/trades'
      path: '/api/trades'
      fullPath: '/api/trades'
      preLoaderRoute: typeof ApiTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-token': {
      id: '/api/track-token'
      path: '/api/track-token'
      fullPath: '/api/track-token'
      preLoaderRoute: typeof ApiTrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token-events': {
      id: '/api/token-events'
      path: '/api/token-events'
      fullPath: '/api/token-events'
      preLoaderRoute: typeof ApiTokenEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals': {
      id: '/api/signals'
      path: '/api/signals'
      fullPath: '/api/signals'
      preLoaderRoute: typeof ApiSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorecard': {
      id: '/api/scorecard'
      path: '/api/scorecard'
      fullPath: '/api/scorecard'
      preLoaderRoute: typeof ApiScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opportunities': {
      id: '/api/opportunities'
      path: '/api/opportunities'
      fullPath: '/api/opportunities'
      preLoaderRoute: typeof ApiOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/klines': {
      id: '/api/klines'
      path: '/api/klines'
      fullPath: '/api/klines'
      preLoaderRoute: typeof ApiKlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forward-test': {
      id: '/api/forward-test'
      path: '/api/forward-test'
      fullPath: '/api/forward-test'
      preLoaderRoute: typeof ApiForwardTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-context': {
      id: '/api/external-context'
      path: '/api/external-context'
      fullPath: '/api/external-context'
      preLoaderRoute: typeof ApiExternalContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/economic-events': {
      id: '/api/economic-events'
      path: '/api/economic-events'
      fullPath: '/api/economic-events'
      preLoaderRoute: typeof ApiEconomicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/derivatives': {
      id: '/api/derivatives'
      path: '/api/derivatives'
      fullPath: '/api/derivatives'
      preLoaderRoute: typeof ApiDerivativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decisions': {
      id: '/api/decisions'
      path: '/api/decisions'
      fullPath: '/api/decisions'
      preLoaderRoute: typeof ApiDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades/$id': {
      id: '/api/trades/$id'
      path: '/$id'
      fullPath: '/api/trades/$id'
      preLoaderRoute: typeof ApiTradesIdRouteImport
      parentRoute: typeof ApiTradesRoute
    }
    '/api/review/forensics': {
      id: '/api/review/forensics'
      path: '/api/review/forensics'
      fullPath: '/api/review/forensics'
      preLoaderRoute: typeof ApiReviewForensicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/analytics': {
      id: '/api/review/analytics'
      path: '/api/review/analytics'
      fullPath: '/api/review/analytics'
      preLoaderRoute: typeof ApiReviewAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/$id': {
      id: '/api/review/$id'
      path: '/api/review/$id'
      fullPath: '/api/review/$id'
      preLoaderRoute: typeof ApiReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/positions/stream': {
      id: '/api/positions/stream'
      path: '/api/positions/stream'
      fullPath: '/api/positions/stream'
      preLoaderRoute: typeof ApiPositionsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/skip-check': {
      id: '/api/execution/skip-check'
      path: '/api/execution/skip-check'
      fullPath: '/api/execution/skip-check'
      preLoaderRoute: typeof ApiExecutionSkipCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/permit': {
      id: '/api/execution/permit'
      path: '/api/execution/permit'
      fullPath: '/api/execution/permit'
      preLoaderRoute: typeof ApiExecutionPermitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/executions': {
      id: '/api/execution/executions'
      path: '/api/execution/executions'
      fullPath: '/api/execution/executions'
      preLoaderRoute: typeof ApiExecutionExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/execute': {
      id: '/api/execution/execute'
      path: '/api/execution/execute'
      fullPath: '/api/execution/execute'
      preLoaderRoute: typeof ApiExecutionExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/constitution': {
      id: '/api/execution/constitution'
      path: '/api/execution/constitution'
      fullPath: '/api/execution/constitution'
      preLoaderRoute: typeof ApiExecutionConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance-review/trades': {
      id: '/api/binance-review/trades'
      path: '/api/binance-review/trades'
      fullPath: '/api/binance-review/trades'
      preLoaderRoute: typeof ApiBinanceReviewTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance-review/sync': {
      id: '/api/binance-review/sync'
      path: '/api/binance-review/sync'
      fullPath: '/api/binance-review/sync'
      preLoaderRoute: typeof ApiBinanceReviewSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance-review/api-key': {
      id: '/api/binance-review/api-key'
      path: '/api/binance-review/api-key'
      fullPath: '/api/binance-review/api-key'
      preLoaderRoute: typeof ApiBinanceReviewApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/telegram': {
      id: '/api/auth/telegram'
      path: '/telegram'
      fullPath: '/api/auth/telegram'
      preLoaderRoute: typeof ApiAuthTelegramRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/ai-desk/analyze-trades': {
      id: '/api/ai-desk/analyze-trades'
      path: '/api/ai-desk/analyze-trades'
      fullPath: '/api/ai-desk/analyze-trades'
      preLoaderRoute: typeof ApiAiDeskAnalyzeTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/forensics/$tradeId': {
      id: '/api/review/forensics/$tradeId'
      path: '/$tradeId'
      fullPath: '/api/review/forensics/$tradeId'
      preLoaderRoute: typeof ApiReviewForensicsTradeIdRouteImport
      parentRoute: typeof ApiReviewForensicsRoute
    }
    '/api/execution/permit/$id': {
      id: '/api/execution/permit/$id'
      path: '/$id'
      fullPath: '/api/execution/permit/$id'
      preLoaderRoute: typeof ApiExecutionPermitIdRouteImport
      parentRoute: typeof ApiExecutionPermitRoute
    }
    '/api/decisions/$id/action': {
      id: '/api/decisions/$id/action'
      path: '/$id/action'
      fullPath: '/api/decisions/$id/action'
      preLoaderRoute: typeof ApiDecisionsIdActionRouteImport
      parentRoute: typeof ApiDecisionsRoute
    }
    '/api/alerts/$id/read': {
      id: '/api/alerts/$id/read'
      path: '/$id/read'
      fullPath: '/api/alerts/$id/read'
      preLoaderRoute: typeof ApiAlertsIdReadRouteImport
      parentRoute: typeof ApiAlertsRoute
    }
  }
}

interface ApiAlertsRouteChildren {
  ApiAlertsIdReadRoute: typeof ApiAlertsIdReadRoute
}

const ApiAlertsRouteChildren: ApiAlertsRouteChildren = {
  ApiAlertsIdReadRoute: ApiAlertsIdReadRoute,
}

const ApiAlertsRouteWithChildren = ApiAlertsRoute._addFileChildren(
  ApiAlertsRouteChildren,
)

interface ApiAuthRouteChildren {
  ApiAuthTelegramRoute: typeof ApiAuthTelegramRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthTelegramRoute: ApiAuthTelegramRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

interface ApiDecisionsRouteChildren {
  ApiDecisionsIdActionRoute: typeof ApiDecisionsIdActionRoute
}

const ApiDecisionsRouteChildren: ApiDecisionsRouteChildren = {
  ApiDecisionsIdActionRoute: ApiDecisionsIdActionRoute,
}

const ApiDecisionsRouteWithChildren = ApiDecisionsRoute._addFileChildren(
  ApiDecisionsRouteChildren,
)

interface ApiTradesRouteChildren {
  ApiTradesIdRoute: typeof ApiTradesIdRoute
}

const ApiTradesRouteChildren: ApiTradesRouteChildren = {
  ApiTradesIdRoute: ApiTradesIdRoute,
}

const ApiTradesRouteWithChildren = ApiTradesRoute._addFileChildren(
  ApiTradesRouteChildren,
)

interface ApiExecutionPermitRouteChildren {
  ApiExecutionPermitIdRoute: typeof ApiExecutionPermitIdRoute
}

const ApiExecutionPermitRouteChildren: ApiExecutionPermitRouteChildren = {
  ApiExecutionPermitIdRoute: ApiExecutionPermitIdRoute,
}

const ApiExecutionPermitRouteWithChildren =
  ApiExecutionPermitRoute._addFileChildren(ApiExecutionPermitRouteChildren)

interface ApiReviewForensicsRouteChildren {
  ApiReviewForensicsTradeIdRoute: typeof ApiReviewForensicsTradeIdRoute
}

const ApiReviewForensicsRouteChildren: ApiReviewForensicsRouteChildren = {
  ApiReviewForensicsTradeIdRoute: ApiReviewForensicsTradeIdRoute,
}

const ApiReviewForensicsRouteWithChildren =
  ApiReviewForensicsRoute._addFileChildren(ApiReviewForensicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BookRoute: BookRoute,
  IdeasRoute: IdeasRoute,
  JournalRoute: JournalRoute,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  RankingsRoute: RankingsRoute,
  RegimeRoute: RegimeRoute,
  ReviewRoute: ReviewRoute,
  RotationRoute: RotationRoute,
  SettingsRoute: SettingsRoute,
  TechnicalRoute: TechnicalRoute,
  TrackerRoute: TrackerRoute,
  TradesRoute: TradesRoute,
  ApiAlertsRoute: ApiAlertsRouteWithChildren,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiDecisionsRoute: ApiDecisionsRouteWithChildren,
  ApiDerivativesRoute: ApiDerivativesRoute,
  ApiEconomicEventsRoute: ApiEconomicEventsRoute,
  ApiExternalContextRoute: ApiExternalContextRoute,
  ApiForwardTestRoute: ApiForwardTestRoute,
  ApiKlinesRoute: ApiKlinesRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiOpportunitiesRoute: ApiOpportunitiesRoute,
  ApiPreferencesRoute: ApiPreferencesRoute,
  ApiScorecardRoute: ApiScorecardRoute,
  ApiSignalsRoute: ApiSignalsRoute,
  ApiTokenEventsRoute: ApiTokenEventsRoute,
  ApiTrackTokenRoute: ApiTrackTokenRoute,
  ApiTradesRoute: ApiTradesRouteWithChildren,
  ApiUniverseRoute: ApiUniverseRoute,
  ApiWatchlistRoute: ApiWatchlistRoute,
  TokenSymbolRoute: TokenSymbolRoute,
  ApiAiDeskAnalyzeTradesRoute: ApiAiDeskAnalyzeTradesRoute,
  ApiBinanceReviewApiKeyRoute: ApiBinanceReviewApiKeyRoute,
  ApiBinanceReviewSyncRoute: ApiBinanceReviewSyncRoute,
  ApiBinanceReviewTradesRoute: ApiBinanceReviewTradesRoute,
  ApiExecutionConstitutionRoute: ApiExecutionConstitutionRoute,
  ApiExecutionExecuteRoute: ApiExecutionExecuteRoute,
  ApiExecutionExecutionsRoute: ApiExecutionExecutionsRoute,
  ApiExecutionPermitRoute: ApiExecutionPermitRouteWithChildren,
  ApiExecutionSkipCheckRoute: ApiExecutionSkipCheckRoute,
  ApiPositionsStreamRoute: ApiPositionsStreamRoute,
  ApiReviewIdRoute: ApiReviewIdRoute,
  ApiReviewAnalyticsRoute: ApiReviewAnalyticsRoute,
  ApiReviewForensicsRoute: ApiReviewForensicsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
