/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TechnicalRouteImport } from './routes/technical'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RotationRouteImport } from './routes/rotation'
import { Route as RegimeRouteImport } from './routes/regime'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenSymbolRouteImport } from './routes/token.$symbol'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiTradesRouteImport } from './routes/api/trades'
import { Route as ApiTrackTokenRouteImport } from './routes/api/track-token'
import { Route as ApiTokenEventsRouteImport } from './routes/api/token-events'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiKlinesRouteImport } from './routes/api/klines'
import { Route as ApiForwardTestRouteImport } from './routes/api/forward-test'
import { Route as ApiExternalContextRouteImport } from './routes/api/external-context'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiTradesIdRouteImport } from './routes/api/trades.$id'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RotationRoute = RotationRouteImport.update({
  id: '/rotation',
  path: '/rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimeRoute = RegimeRouteImport.update({
  id: '/regime',
  path: '/regime',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenSymbolRoute = TokenSymbolRouteImport.update({
  id: '/token/$symbol',
  path: '/token/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesRoute = ApiTradesRouteImport.update({
  id: '/api/trades',
  path: '/api/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackTokenRoute = ApiTrackTokenRouteImport.update({
  id: '/api/track-token',
  path: '/api/track-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenEventsRoute = ApiTokenEventsRouteImport.update({
  id: '/api/token-events',
  path: '/api/token-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKlinesRoute = ApiKlinesRouteImport.update({
  id: '/api/klines',
  path: '/api/klines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForwardTestRoute = ApiForwardTestRouteImport.update({
  id: '/api/forward-test',
  path: '/api/forward-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalContextRoute = ApiExternalContextRouteImport.update({
  id: '/api/external-context',
  path: '/api/external-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesIdRoute = ApiTradesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTradesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/trades/$id': typeof ApiTradesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/trades/$id': typeof ApiTradesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/trades/$id': typeof ApiTradesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/api/auth'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/notifications'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/trades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/api/auth'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/notifications'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/trades/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/api/auth'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/notifications'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/trades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  RankingsRoute: typeof RankingsRoute
  RegimeRoute: typeof RegimeRoute
  RotationRoute: typeof RotationRoute
  SettingsRoute: typeof SettingsRoute
  TechnicalRoute: typeof TechnicalRoute
  TrackerRoute: typeof TrackerRoute
  TradesRoute: typeof TradesRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiExternalContextRoute: typeof ApiExternalContextRoute
  ApiForwardTestRoute: typeof ApiForwardTestRoute
  ApiKlinesRoute: typeof ApiKlinesRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiTokenEventsRoute: typeof ApiTokenEventsRoute
  ApiTrackTokenRoute: typeof ApiTrackTokenRoute
  ApiTradesRoute: typeof ApiTradesRouteWithChildren
  ApiWatchlistRoute: typeof ApiWatchlistRoute
  TokenSymbolRoute: typeof TokenSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotation': {
      id: '/rotation'
      path: '/rotation'
      fullPath: '/rotation'
      preLoaderRoute: typeof RotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regime': {
      id: '/regime'
      path: '/regime'
      fullPath: '/regime'
      preLoaderRoute: typeof RegimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$symbol': {
      id: '/token/$symbol'
      path: '/token/$symbol'
      fullPath: '/token/$symbol'
      preLoaderRoute: typeof TokenSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades': {
      id: '/api/trades'
      path: '/api/trades'
      fullPath: '/api/trades'
      preLoaderRoute: typeof ApiTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-token': {
      id: '/api/track-token'
      path: '/api/track-token'
      fullPath: '/api/track-token'
      preLoaderRoute: typeof ApiTrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token-events': {
      id: '/api/token-events'
      path: '/api/token-events'
      fullPath: '/api/token-events'
      preLoaderRoute: typeof ApiTokenEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/klines': {
      id: '/api/klines'
      path: '/api/klines'
      fullPath: '/api/klines'
      preLoaderRoute: typeof ApiKlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forward-test': {
      id: '/api/forward-test'
      path: '/api/forward-test'
      fullPath: '/api/forward-test'
      preLoaderRoute: typeof ApiForwardTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-context': {
      id: '/api/external-context'
      path: '/api/external-context'
      fullPath: '/api/external-context'
      preLoaderRoute: typeof ApiExternalContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades/$id': {
      id: '/api/trades/$id'
      path: '/$id'
      fullPath: '/api/trades/$id'
      preLoaderRoute: typeof ApiTradesIdRouteImport
      parentRoute: typeof ApiTradesRoute
    }
  }
}

interface ApiTradesRouteChildren {
  ApiTradesIdRoute: typeof ApiTradesIdRoute
}

const ApiTradesRouteChildren: ApiTradesRouteChildren = {
  ApiTradesIdRoute: ApiTradesIdRoute,
}

const ApiTradesRouteWithChildren = ApiTradesRoute._addFileChildren(
  ApiTradesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  RankingsRoute: RankingsRoute,
  RegimeRoute: RegimeRoute,
  RotationRoute: RotationRoute,
  SettingsRoute: SettingsRoute,
  TechnicalRoute: TechnicalRoute,
  TrackerRoute: TrackerRoute,
  TradesRoute: TradesRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiExternalContextRoute: ApiExternalContextRoute,
  ApiForwardTestRoute: ApiForwardTestRoute,
  ApiKlinesRoute: ApiKlinesRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiTokenEventsRoute: ApiTokenEventsRoute,
  ApiTrackTokenRoute: ApiTrackTokenRoute,
  ApiTradesRoute: ApiTradesRouteWithChildren,
  ApiWatchlistRoute: ApiWatchlistRoute,
  TokenSymbolRoute: TokenSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
