/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TechnicalRouteImport } from './routes/technical'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RotationRouteImport } from './routes/rotation'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegimeRouteImport } from './routes/regime'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenSymbolRouteImport } from './routes/token.$symbol'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiTradesRouteImport } from './routes/api/trades'
import { Route as ApiTrackTokenRouteImport } from './routes/api/track-token'
import { Route as ApiTokenEventsRouteImport } from './routes/api/token-events'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiMarketContextRouteImport } from './routes/api/market-context'
import { Route as ApiKlinesRouteImport } from './routes/api/klines'
import { Route as ApiForwardTestRouteImport } from './routes/api/forward-test'
import { Route as ApiExternalContextRouteImport } from './routes/api/external-context'
import { Route as ApiEvidenceRouteImport } from './routes/api/evidence'
import { Route as ApiEconomicEventsRouteImport } from './routes/api/economic-events'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiTradesIdRouteImport } from './routes/api/trades.$id'
import { Route as ApiReviewAnalyticsRouteImport } from './routes/api/review.analytics'
import { Route as ApiReviewIdRouteImport } from './routes/api/review.$id'
import { Route as ApiExecutionPermitRouteImport } from './routes/api/execution.permit'
import { Route as ApiExecutionExecutionsRouteImport } from './routes/api/execution.executions'
import { Route as ApiExecutionExecuteRouteImport } from './routes/api/execution.execute'
import { Route as ApiExecutionConstitutionRouteImport } from './routes/api/execution.constitution'
import { Route as ApiBinanceReviewTradesRouteImport } from './routes/api/binance-review.trades'
import { Route as ApiBinanceReviewSyncRouteImport } from './routes/api/binance-review.sync'
import { Route as ApiBinanceReviewApiKeyRouteImport } from './routes/api/binance-review.api-key'
import { Route as ApiExecutionPermitIdRouteImport } from './routes/api/execution.permit.$id'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RotationRoute = RotationRouteImport.update({
  id: '/rotation',
  path: '/rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimeRoute = RegimeRouteImport.update({
  id: '/regime',
  path: '/regime',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenSymbolRoute = TokenSymbolRouteImport.update({
  id: '/token/$symbol',
  path: '/token/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesRoute = ApiTradesRouteImport.update({
  id: '/api/trades',
  path: '/api/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackTokenRoute = ApiTrackTokenRouteImport.update({
  id: '/api/track-token',
  path: '/api/track-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenEventsRoute = ApiTokenEventsRouteImport.update({
  id: '/api/token-events',
  path: '/api/token-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketContextRoute = ApiMarketContextRouteImport.update({
  id: '/api/market-context',
  path: '/api/market-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKlinesRoute = ApiKlinesRouteImport.update({
  id: '/api/klines',
  path: '/api/klines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForwardTestRoute = ApiForwardTestRouteImport.update({
  id: '/api/forward-test',
  path: '/api/forward-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalContextRoute = ApiExternalContextRouteImport.update({
  id: '/api/external-context',
  path: '/api/external-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceRoute = ApiEvidenceRouteImport.update({
  id: '/api/evidence',
  path: '/api/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEconomicEventsRoute = ApiEconomicEventsRouteImport.update({
  id: '/api/economic-events',
  path: '/api/economic-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesIdRoute = ApiTradesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTradesRoute,
} as any)
const ApiReviewAnalyticsRoute = ApiReviewAnalyticsRouteImport.update({
  id: '/api/review/analytics',
  path: '/api/review/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewIdRoute = ApiReviewIdRouteImport.update({
  id: '/api/review/$id',
  path: '/api/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionPermitRoute = ApiExecutionPermitRouteImport.update({
  id: '/api/execution/permit',
  path: '/api/execution/permit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionExecutionsRoute = ApiExecutionExecutionsRouteImport.update({
  id: '/api/execution/executions',
  path: '/api/execution/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionExecuteRoute = ApiExecutionExecuteRouteImport.update({
  id: '/api/execution/execute',
  path: '/api/execution/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionConstitutionRoute =
  ApiExecutionConstitutionRouteImport.update({
    id: '/api/execution/constitution',
    path: '/api/execution/constitution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBinanceReviewTradesRoute = ApiBinanceReviewTradesRouteImport.update({
  id: '/api/binance-review/trades',
  path: '/api/binance-review/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceReviewSyncRoute = ApiBinanceReviewSyncRouteImport.update({
  id: '/api/binance-review/sync',
  path: '/api/binance-review/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceReviewApiKeyRoute = ApiBinanceReviewApiKeyRouteImport.update({
  id: '/api/binance-review/api-key',
  path: '/api/binance-review/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecutionPermitIdRoute = ApiExecutionPermitIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExecutionPermitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/review': typeof ReviewRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/evidence': typeof ApiEvidenceRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/market-context': typeof ApiMarketContextRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/binance-review/api-key': typeof ApiBinanceReviewApiKeyRoute
  '/api/binance-review/sync': typeof ApiBinanceReviewSyncRoute
  '/api/binance-review/trades': typeof ApiBinanceReviewTradesRoute
  '/api/execution/constitution': typeof ApiExecutionConstitutionRoute
  '/api/execution/execute': typeof ApiExecutionExecuteRoute
  '/api/execution/executions': typeof ApiExecutionExecutionsRoute
  '/api/execution/permit': typeof ApiExecutionPermitRouteWithChildren
  '/api/review/$id': typeof ApiReviewIdRoute
  '/api/review/analytics': typeof ApiReviewAnalyticsRoute
  '/api/trades/$id': typeof ApiTradesIdRoute
  '/api/execution/permit/$id': typeof ApiExecutionPermitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/review': typeof ReviewRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/evidence': typeof ApiEvidenceRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/market-context': typeof ApiMarketContextRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/binance-review/api-key': typeof ApiBinanceReviewApiKeyRoute
  '/api/binance-review/sync': typeof ApiBinanceReviewSyncRoute
  '/api/binance-review/trades': typeof ApiBinanceReviewTradesRoute
  '/api/execution/constitution': typeof ApiExecutionConstitutionRoute
  '/api/execution/execute': typeof ApiExecutionExecuteRoute
  '/api/execution/executions': typeof ApiExecutionExecutionsRoute
  '/api/execution/permit': typeof ApiExecutionPermitRouteWithChildren
  '/api/review/$id': typeof ApiReviewIdRoute
  '/api/review/analytics': typeof ApiReviewAnalyticsRoute
  '/api/trades/$id': typeof ApiTradesIdRoute
  '/api/execution/permit/$id': typeof ApiExecutionPermitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/review': typeof ReviewRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/tracker': typeof TrackerRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/evidence': typeof ApiEvidenceRoute
  '/api/external-context': typeof ApiExternalContextRoute
  '/api/forward-test': typeof ApiForwardTestRoute
  '/api/klines': typeof ApiKlinesRoute
  '/api/market-context': typeof ApiMarketContextRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/token-events': typeof ApiTokenEventsRoute
  '/api/track-token': typeof ApiTrackTokenRoute
  '/api/trades': typeof ApiTradesRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRoute
  '/token/$symbol': typeof TokenSymbolRoute
  '/api/binance-review/api-key': typeof ApiBinanceReviewApiKeyRoute
  '/api/binance-review/sync': typeof ApiBinanceReviewSyncRoute
  '/api/binance-review/trades': typeof ApiBinanceReviewTradesRoute
  '/api/execution/constitution': typeof ApiExecutionConstitutionRoute
  '/api/execution/execute': typeof ApiExecutionExecuteRoute
  '/api/execution/executions': typeof ApiExecutionExecutionsRoute
  '/api/execution/permit': typeof ApiExecutionPermitRouteWithChildren
  '/api/review/$id': typeof ApiReviewIdRoute
  '/api/review/analytics': typeof ApiReviewAnalyticsRoute
  '/api/trades/$id': typeof ApiTradesIdRoute
  '/api/execution/permit/$id': typeof ApiExecutionPermitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/discover'
    | '/events'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/review'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/watchlist'
    | '/api/auth'
    | '/api/economic-events'
    | '/api/evidence'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/market-context'
    | '/api/notifications'
    | '/api/preferences'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/binance-review/api-key'
    | '/api/binance-review/sync'
    | '/api/binance-review/trades'
    | '/api/execution/constitution'
    | '/api/execution/execute'
    | '/api/execution/executions'
    | '/api/execution/permit'
    | '/api/review/$id'
    | '/api/review/analytics'
    | '/api/trades/$id'
    | '/api/execution/permit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/discover'
    | '/events'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/review'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/watchlist'
    | '/api/auth'
    | '/api/economic-events'
    | '/api/evidence'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/market-context'
    | '/api/notifications'
    | '/api/preferences'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/binance-review/api-key'
    | '/api/binance-review/sync'
    | '/api/binance-review/trades'
    | '/api/execution/constitution'
    | '/api/execution/execute'
    | '/api/execution/executions'
    | '/api/execution/permit'
    | '/api/review/$id'
    | '/api/review/analytics'
    | '/api/trades/$id'
    | '/api/execution/permit/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/discover'
    | '/events'
    | '/login'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/review'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/tracker'
    | '/trades'
    | '/watchlist'
    | '/api/auth'
    | '/api/economic-events'
    | '/api/evidence'
    | '/api/external-context'
    | '/api/forward-test'
    | '/api/klines'
    | '/api/market-context'
    | '/api/notifications'
    | '/api/preferences'
    | '/api/token-events'
    | '/api/track-token'
    | '/api/trades'
    | '/api/watchlist'
    | '/token/$symbol'
    | '/api/binance-review/api-key'
    | '/api/binance-review/sync'
    | '/api/binance-review/trades'
    | '/api/execution/constitution'
    | '/api/execution/execute'
    | '/api/execution/executions'
    | '/api/execution/permit'
    | '/api/review/$id'
    | '/api/review/analytics'
    | '/api/trades/$id'
    | '/api/execution/permit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DiscoverRoute: typeof DiscoverRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  RankingsRoute: typeof RankingsRoute
  RegimeRoute: typeof RegimeRoute
  ReviewRoute: typeof ReviewRoute
  RotationRoute: typeof RotationRoute
  SettingsRoute: typeof SettingsRoute
  TechnicalRoute: typeof TechnicalRoute
  TrackerRoute: typeof TrackerRoute
  TradesRoute: typeof TradesRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiEconomicEventsRoute: typeof ApiEconomicEventsRoute
  ApiEvidenceRoute: typeof ApiEvidenceRoute
  ApiExternalContextRoute: typeof ApiExternalContextRoute
  ApiForwardTestRoute: typeof ApiForwardTestRoute
  ApiKlinesRoute: typeof ApiKlinesRoute
  ApiMarketContextRoute: typeof ApiMarketContextRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  ApiTokenEventsRoute: typeof ApiTokenEventsRoute
  ApiTrackTokenRoute: typeof ApiTrackTokenRoute
  ApiTradesRoute: typeof ApiTradesRouteWithChildren
  ApiWatchlistRoute: typeof ApiWatchlistRoute
  TokenSymbolRoute: typeof TokenSymbolRoute
  ApiBinanceReviewApiKeyRoute: typeof ApiBinanceReviewApiKeyRoute
  ApiBinanceReviewSyncRoute: typeof ApiBinanceReviewSyncRoute
  ApiBinanceReviewTradesRoute: typeof ApiBinanceReviewTradesRoute
  ApiExecutionConstitutionRoute: typeof ApiExecutionConstitutionRoute
  ApiExecutionExecuteRoute: typeof ApiExecutionExecuteRoute
  ApiExecutionExecutionsRoute: typeof ApiExecutionExecutionsRoute
  ApiExecutionPermitRoute: typeof ApiExecutionPermitRouteWithChildren
  ApiReviewIdRoute: typeof ApiReviewIdRoute
  ApiReviewAnalyticsRoute: typeof ApiReviewAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotation': {
      id: '/rotation'
      path: '/rotation'
      fullPath: '/rotation'
      preLoaderRoute: typeof RotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regime': {
      id: '/regime'
      path: '/regime'
      fullPath: '/regime'
      preLoaderRoute: typeof RegimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$symbol': {
      id: '/token/$symbol'
      path: '/token/$symbol'
      fullPath: '/token/$symbol'
      preLoaderRoute: typeof TokenSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades': {
      id: '/api/trades'
      path: '/api/trades'
      fullPath: '/api/trades'
      preLoaderRoute: typeof ApiTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-token': {
      id: '/api/track-token'
      path: '/api/track-token'
      fullPath: '/api/track-token'
      preLoaderRoute: typeof ApiTrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token-events': {
      id: '/api/token-events'
      path: '/api/token-events'
      fullPath: '/api/token-events'
      preLoaderRoute: typeof ApiTokenEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-context': {
      id: '/api/market-context'
      path: '/api/market-context'
      fullPath: '/api/market-context'
      preLoaderRoute: typeof ApiMarketContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/klines': {
      id: '/api/klines'
      path: '/api/klines'
      fullPath: '/api/klines'
      preLoaderRoute: typeof ApiKlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forward-test': {
      id: '/api/forward-test'
      path: '/api/forward-test'
      fullPath: '/api/forward-test'
      preLoaderRoute: typeof ApiForwardTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-context': {
      id: '/api/external-context'
      path: '/api/external-context'
      fullPath: '/api/external-context'
      preLoaderRoute: typeof ApiExternalContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence': {
      id: '/api/evidence'
      path: '/api/evidence'
      fullPath: '/api/evidence'
      preLoaderRoute: typeof ApiEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/economic-events': {
      id: '/api/economic-events'
      path: '/api/economic-events'
      fullPath: '/api/economic-events'
      preLoaderRoute: typeof ApiEconomicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades/$id': {
      id: '/api/trades/$id'
      path: '/$id'
      fullPath: '/api/trades/$id'
      preLoaderRoute: typeof ApiTradesIdRouteImport
      parentRoute: typeof ApiTradesRoute
    }
    '/api/review/analytics': {
      id: '/api/review/analytics'
      path: '/api/review/analytics'
      fullPath: '/api/review/analytics'
      preLoaderRoute: typeof ApiReviewAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/$id': {
      id: '/api/review/$id'
      path: '/api/review/$id'
      fullPath: '/api/review/$id'
      preLoaderRoute: typeof ApiReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/permit': {
      id: '/api/execution/permit'
      path: '/api/execution/permit'
      fullPath: '/api/execution/permit'
      preLoaderRoute: typeof ApiExecutionPermitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/executions': {
      id: '/api/execution/executions'
      path: '/api/execution/executions'
      fullPath: '/api/execution/executions'
      preLoaderRoute: typeof ApiExecutionExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/execute': {
      id: '/api/execution/execute'
      path: '/api/execution/execute'
      fullPath: '/api/execution/execute'
      preLoaderRoute: typeof ApiExecutionExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/constitution': {
      id: '/api/execution/constitution'
      path: '/api/execution/constitution'
      fullPath: '/api/execution/constitution'
      preLoaderRoute: typeof ApiExecutionConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance-review/trades': {
      id: '/api/binance-review/trades'
      path: '/api/binance-review/trades'
      fullPath: '/api/binance-review/trades'
      preLoaderRoute: typeof ApiBinanceReviewTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance-review/sync': {
      id: '/api/binance-review/sync'
      path: '/api/binance-review/sync'
      fullPath: '/api/binance-review/sync'
      preLoaderRoute: typeof ApiBinanceReviewSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance-review/api-key': {
      id: '/api/binance-review/api-key'
      path: '/api/binance-review/api-key'
      fullPath: '/api/binance-review/api-key'
      preLoaderRoute: typeof ApiBinanceReviewApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execution/permit/$id': {
      id: '/api/execution/permit/$id'
      path: '/$id'
      fullPath: '/api/execution/permit/$id'
      preLoaderRoute: typeof ApiExecutionPermitIdRouteImport
      parentRoute: typeof ApiExecutionPermitRoute
    }
  }
}

interface ApiTradesRouteChildren {
  ApiTradesIdRoute: typeof ApiTradesIdRoute
}

const ApiTradesRouteChildren: ApiTradesRouteChildren = {
  ApiTradesIdRoute: ApiTradesIdRoute,
}

const ApiTradesRouteWithChildren = ApiTradesRoute._addFileChildren(
  ApiTradesRouteChildren,
)

interface ApiExecutionPermitRouteChildren {
  ApiExecutionPermitIdRoute: typeof ApiExecutionPermitIdRoute
}

const ApiExecutionPermitRouteChildren: ApiExecutionPermitRouteChildren = {
  ApiExecutionPermitIdRoute: ApiExecutionPermitIdRoute,
}

const ApiExecutionPermitRouteWithChildren =
  ApiExecutionPermitRoute._addFileChildren(ApiExecutionPermitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DiscoverRoute: DiscoverRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  RankingsRoute: RankingsRoute,
  RegimeRoute: RegimeRoute,
  ReviewRoute: ReviewRoute,
  RotationRoute: RotationRoute,
  SettingsRoute: SettingsRoute,
  TechnicalRoute: TechnicalRoute,
  TrackerRoute: TrackerRoute,
  TradesRoute: TradesRoute,
  WatchlistRoute: WatchlistRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiEconomicEventsRoute: ApiEconomicEventsRoute,
  ApiEvidenceRoute: ApiEvidenceRoute,
  ApiExternalContextRoute: ApiExternalContextRoute,
  ApiForwardTestRoute: ApiForwardTestRoute,
  ApiKlinesRoute: ApiKlinesRoute,
  ApiMarketContextRoute: ApiMarketContextRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiPreferencesRoute: ApiPreferencesRoute,
  ApiTokenEventsRoute: ApiTokenEventsRoute,
  ApiTrackTokenRoute: ApiTrackTokenRoute,
  ApiTradesRoute: ApiTradesRouteWithChildren,
  ApiWatchlistRoute: ApiWatchlistRoute,
  TokenSymbolRoute: TokenSymbolRoute,
  ApiBinanceReviewApiKeyRoute: ApiBinanceReviewApiKeyRoute,
  ApiBinanceReviewSyncRoute: ApiBinanceReviewSyncRoute,
  ApiBinanceReviewTradesRoute: ApiBinanceReviewTradesRoute,
  ApiExecutionConstitutionRoute: ApiExecutionConstitutionRoute,
  ApiExecutionExecuteRoute: ApiExecutionExecuteRoute,
  ApiExecutionExecutionsRoute: ApiExecutionExecutionsRoute,
  ApiExecutionPermitRoute: ApiExecutionPermitRouteWithChildren,
  ApiReviewIdRoute: ApiReviewIdRoute,
  ApiReviewAnalyticsRoute: ApiReviewAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
