"""Alembic migration template."""

revision = "b8dd766d556f"
down_revision = "52bfd16edb58"
branch_labels = None
depends_on = None


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('signals_pkey'))
    )
    op.create_index(op.f('signals_token_id_idx'), 'signals', ['token_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('change_24h', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tokens_pkey'))
    )
    op.create_index(op.f('tokens_symbol_idx'), 'tokens', ['symbol'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trades_pkey'))
    )
    op.create_index(op.f('trades_user_id_idx'), 'trades', ['user_id'], unique=False)
    op.drop_table('engine_run')
    op.drop_index(op.f('token_event_created_idx'), table_name='token_event')
    op.drop_index(op.f('token_event_dedup_uniq'), table_name='token_event')
    op.drop_index(op.f('token_event_symbol_idx'), table_name='token_event')
    op.drop_table('token_event')
    op.drop_index(op.f('eval_log_bt_idx'), table_name='eval_log')
    op.drop_index(op.f('eval_log_lookup_idx'), table_name='eval_log')
    op.drop_index(op.f('eval_log_verdict_idx'), table_name='eval_log')
    op.drop_table('eval_log')
    op.drop_index(op.f('tracked_owner_idx'), table_name='tracked_signal')
    op.drop_table('tracked_signal')
    op.drop_index(op.f('catalyst_event_dedup_uniq'), table_name='catalyst_event')
    op.drop_index(op.f('catalyst_event_occurs_idx'), table_name='catalyst_event')
    op.drop_index(op.f('catalyst_event_symbol_occurs_idx'), table_name='catalyst_event')
    op.drop_table('catalyst_event')
    op.drop_index(op.f('backtest_kind_idx'), table_name='backtest_run')
    op.drop_table('backtest_run')
    op.drop_table('login_tokens')
    op.drop_table('invites')
    op.drop_table('sessions')
    op.drop_index(op.f('user_watchlist_symbol_idx'), table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_table('_migrations')
    op.drop_index(op.f('shadow_active_uniq'), table_name='shadow_signal', postgresql_where="(status = 'active'::text)")
    op.drop_index(op.f('shadow_combo_idx'), table_name='shadow_signal')
    op.drop_index(op.f('shadow_group_idx'), table_name='shadow_signal')
    op.drop_index(op.f('shadow_open_idx'), table_name='shadow_signal')
    op.drop_table('shadow_signal')
    op.drop_index(op.f('market_context_fetched_idx'), table_name='market_context_snapshot')
    op.drop_table('market_context_snapshot')
    op.drop_index(op.f('verdict_hold_scope_idx'), table_name='verdict_hold')
    op.drop_table('verdict_hold')
    op.drop_table('ingest_state')
    op.drop_index(op.f('anticipatory_active_uniq'), table_name='anticipatory_signal', postgresql_where="(status = ANY (ARRAY['pending'::text, 'filled'::text]))")
    op.drop_index(op.f('anticipatory_group_idx'), table_name='anticipatory_signal')
    op.drop_index(op.f('anticipatory_open_idx'), table_name='anticipatory_signal')
    op.drop_table('anticipatory_signal')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_invited_by_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'invited_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_invited_by_fkey'), 'users', 'users', ['invited_by'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'display_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'hashed_password')
    op.create_table('anticipatory_signal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('market', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setup_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('regime', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('verdict', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('objective', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('objective_strength', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('zone_freshness', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reward_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('filled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('result_r', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('engine_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('config_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('git_sha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engine_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['engine_run_id'], ['engine_run.id'], name=op.f('anticipatory_signal_engine_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('anticipatory_signal_pkey'))
    )
    op.create_index(op.f('anticipatory_open_idx'), 'anticipatory_signal', ['status'], unique=False)
    op.create_index(op.f('anticipatory_group_idx'), 'anticipatory_signal', ['symbol', 'timeframe', 'market'], unique=False)
    op.create_index(op.f('anticipatory_active_uniq'), 'anticipatory_signal', ['symbol', 'market', 'intent'], unique=True, postgresql_where="(status = ANY (ARRAY['pending'::text, 'filled'::text]))")
    op.create_table('ingest_state',
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_ok_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_error_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('source', name=op.f('ingest_state_pkey'))
    )
    op.create_table('verdict_hold',
    sa.Column('hold_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('market', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('hold_key', name=op.f('verdict_hold_pkey'))
    )
    op.create_index(op.f('verdict_hold_scope_idx'), 'verdict_hold', ['symbol', 'market'], unique=False)
    op.create_table('market_context_snapshot',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('total_mcap_usd', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('btc_dominance', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('eth_dominance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('mcap_change_24h_pct', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'coingecko'::text"), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('market_context_snapshot_pkey'))
    )
    op.create_index(op.f('market_context_fetched_idx'), 'market_context_snapshot', [sa.literal_column('fetched_at DESC')], unique=False)
    op.create_table('shadow_signal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('market', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setup_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('regime', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('target1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('target2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('objective_resolved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('result_r', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('engine_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('config_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('git_sha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engine_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['engine_run_id'], ['engine_run.id'], name=op.f('shadow_signal_engine_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shadow_signal_pkey'))
    )
    op.create_index(op.f('shadow_open_idx'), 'shadow_signal', ['status'], unique=False)
    op.create_index(op.f('shadow_group_idx'), 'shadow_signal', ['symbol', 'timeframe', 'market'], unique=False)
    op.create_index(op.f('shadow_combo_idx'), 'shadow_signal', ['engine_version', 'setup_type', 'regime'], unique=False)
    op.create_index(op.f('shadow_active_uniq'), 'shadow_signal', ['symbol', 'market', 'intent'], unique=True, postgresql_where="(status = 'active'::text)")
    op.create_table('_migrations',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('_migrations_pkey'))
    )
    op.create_table('user_watchlist',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_watchlist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'symbol', name=op.f('user_watchlist_pkey'))
    )
    op.create_index(op.f('user_watchlist_symbol_idx'), 'user_watchlist', ['symbol'], unique=False)
    op.create_table('sessions',
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('sessions_pkey'))
    )
    op.create_table('invites',
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('redeemed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('redeemed_user', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('invites_created_by_fkey')),
    sa.ForeignKeyConstraint(['redeemed_user'], ['users.id'], name=op.f('invites_redeemed_user_fkey')),
    sa.PrimaryKeyConstraint('token', name=op.f('invites_pkey'))
    )
    op.create_table('login_tokens',
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('login_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('login_tokens_pkey'))
    )
    op.create_table('backtest_run',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engine_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('config_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('git_sha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('gate_results_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verdict', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('backtest_run_pkey'))
    )
    op.create_index(op.f('backtest_kind_idx'), 'backtest_run', ['kind', 'engine_version'], unique=False)
    op.create_table('catalyst_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('occurs_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credibility', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('percent_of_supply', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dedup_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('catalyst_event_pkey'))
    )
    op.create_index(op.f('catalyst_event_symbol_occurs_idx'), 'catalyst_event', ['symbol', 'occurs_at'], unique=False)
    op.create_index(op.f('catalyst_event_occurs_idx'), 'catalyst_event', ['occurs_at'], unique=False)
    op.create_index(op.f('catalyst_event_dedup_uniq'), 'catalyst_event', ['dedup_key'], unique=True)
    op.create_table('tracked_signal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setup_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('market', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entry_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('target1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('target2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence_at_follow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('followed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('result_r', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('engine_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('config_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('git_sha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('tracked_signal_owner_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.token'], name=op.f('tracked_signal_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tracked_signal_pkey'))
    )
    op.create_index(op.f('tracked_owner_idx'), 'tracked_signal', ['owner_id', 'status'], unique=False)
    op.create_table('eval_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('engine_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('evaluated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('market', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('verdict', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('setup_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('regime', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bt_win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bt_expectancy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bt_avg_r', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bt_total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bt_low_sample', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('no_trade_reasons', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('engine_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('config_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('git_sha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['engine_run_id'], ['engine_run.id'], name=op.f('eval_log_engine_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('eval_log_pkey'))
    )
    op.create_index(op.f('eval_log_verdict_idx'), 'eval_log', ['verdict'], unique=False)
    op.create_index(op.f('eval_log_lookup_idx'), 'eval_log', ['symbol', 'market', 'intent', 'evaluated_at'], unique=False)
    op.create_index(op.f('eval_log_bt_idx'), 'eval_log', ['bt_win_rate', 'bt_total_trades'], unique=False)
    op.create_table('token_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dedup_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_event_pkey'))
    )
    op.create_index(op.f('token_event_symbol_idx'), 'token_event', ['symbol', sa.literal_column('published_at DESC')], unique=False)
    op.create_index(op.f('token_event_dedup_uniq'), 'token_event', ['dedup_key'], unique=True)
    op.create_index(op.f('token_event_created_idx'), 'token_event', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('engine_run',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('engine_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('config_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('git_sha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('universe_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'ok'::text"), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('engine_run_pkey'))
    )
    op.drop_index(op.f('trades_user_id_idx'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('tokens_symbol_idx'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('signals_token_id_idx'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###