"""Discover forward-test recorder: setups + append-only lifecycle events.

Hand-written rather than autogenerated: `--autogenerate` on this database
proposes recreating unrelated tables it cannot see, so the safe move is to add
exactly the two new tables and nothing else.

`forward_test_setups` holds the immutable hypothesis captured at detection plus
its lifecycle/outcome; `forward_test_events` is insert-only history. Kept
separate from the engine's own `shadow_record` plane — different detector,
different question.
"""

revision = "d7f1c2a9b304"
down_revision = "e1f2a3b4c5d6"
branch_labels = None
depends_on = None


import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    op.create_table(
        "forward_test_setups",
        sa.Column("id", postgresql.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("setup_key", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("market", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        # ── the hypothesis, written once and never updated ──
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("combo", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("families", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("entry_low", sa.Double(), nullable=False),
        sa.Column("entry_high", sa.Double(), nullable=False),
        sa.Column("reference_entry", sa.Double(), nullable=False),
        sa.Column("initial_invalidation", sa.Double(), nullable=False),
        sa.Column("target", sa.Double(), nullable=False),
        sa.Column("target_kind", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("potential_rr", sa.Double(), nullable=False),
        sa.Column("htf_bias", sa.Text(), nullable=False),
        sa.Column("htf_agreement", sa.Double(), nullable=False),
        sa.Column("alignment", sa.Text(), nullable=False),
        sa.Column("alignment_level", sa.Text(), nullable=False),
        sa.Column("structure_trend", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        # ── provenance ──
        sa.Column("strategy_version", sa.Text(), nullable=False),
        sa.Column("engine_version", sa.Text(), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("git_sha", sa.Text(), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        # ── lifecycle ──
        sa.Column("zone_touched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entry_price", sa.Double(), nullable=True),
        sa.Column("active_stop", sa.Double(), nullable=False),
        sa.Column("trailing_mode", sa.Text(), nullable=False),
        sa.Column("trailing_activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trailing_updates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        # ── outcome ──
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_price", sa.Double(), nullable=True),
        sa.Column("exit_reason", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("realized_r", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("mfe_pct", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("mae_pct", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("mfe_r", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("mae_r", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("pending_mfe_pct", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("pending_mae_pct", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("touched_zone", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("event_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_price", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="forward_test_setups_pkey"),
        sa.UniqueConstraint("setup_key", name="forward_test_setups_setup_key_key"),
    )
    op.create_index("forward_test_setups_symbol_idx", "forward_test_setups", ["symbol"])
    op.create_index("forward_test_setups_mode_idx", "forward_test_setups", ["mode"])
    op.create_index("forward_test_setups_status_idx", "forward_test_setups", ["status"])
    op.create_index("forward_test_setups_detected_at_idx", "forward_test_setups", ["detected_at"])
    op.create_index(
        "forward_test_setups_strategy_idx",
        "forward_test_setups",
        ["strategy_version", "config_hash"],
    )
    op.create_index(
        "forward_test_setups_feed_idx", "forward_test_setups", ["mode", "status", "detected_at"]
    )

    op.create_table(
        "forward_test_events",
        sa.Column("id", postgresql.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("setup_id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Double(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["setup_id"],
            ["forward_test_setups.id"],
            name="forward_test_events_setup_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="forward_test_events_pkey"),
    )
    op.create_index("forward_test_events_setup_idx", "forward_test_events", ["setup_id", "ts"])
    op.create_index("forward_test_events_type_idx", "forward_test_events", ["type"])


def downgrade() -> None:
    op.drop_table("forward_test_events")
    op.drop_table("forward_test_setups")
