/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalRouteImport } from './routes/technical'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RotationRouteImport } from './routes/rotation'
import { Route as RegimeRouteImport } from './routes/regime'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenSymbolRouteImport } from './routes/token.$symbol'
import { Route as ApiKlinesRouteImport } from './routes/api/klines'

const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RotationRoute = RotationRouteImport.update({
  id: '/rotation',
  path: '/rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimeRoute = RegimeRouteImport.update({
  id: '/regime',
  path: '/regime',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenSymbolRoute = TokenSymbolRouteImport.update({
  id: '/token/$symbol',
  path: '/token/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKlinesRoute = ApiKlinesRouteImport.update({
  id: '/api/klines',
  path: '/api/klines',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/api/klines': typeof ApiKlinesRoute
  '/token/$symbol': typeof TokenSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/api/klines': typeof ApiKlinesRoute
  '/token/$symbol': typeof TokenSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/regime': typeof RegimeRoute
  '/rotation': typeof RotationRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/api/klines': typeof ApiKlinesRoute
  '/token/$symbol': typeof TokenSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/api/klines'
    | '/token/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/api/klines'
    | '/token/$symbol'
  id:
    | '__root__'
    | '/'
    | '/markets'
    | '/news'
    | '/rankings'
    | '/regime'
    | '/rotation'
    | '/settings'
    | '/technical'
    | '/api/klines'
    | '/token/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  RankingsRoute: typeof RankingsRoute
  RegimeRoute: typeof RegimeRoute
  RotationRoute: typeof RotationRoute
  SettingsRoute: typeof SettingsRoute
  TechnicalRoute: typeof TechnicalRoute
  ApiKlinesRoute: typeof ApiKlinesRoute
  TokenSymbolRoute: typeof TokenSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotation': {
      id: '/rotation'
      path: '/rotation'
      fullPath: '/rotation'
      preLoaderRoute: typeof RotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regime': {
      id: '/regime'
      path: '/regime'
      fullPath: '/regime'
      preLoaderRoute: typeof RegimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$symbol': {
      id: '/token/$symbol'
      path: '/token/$symbol'
      fullPath: '/token/$symbol'
      preLoaderRoute: typeof TokenSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/klines': {
      id: '/api/klines'
      path: '/api/klines'
      fullPath: '/api/klines'
      preLoaderRoute: typeof ApiKlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  RankingsRoute: RankingsRoute,
  RegimeRoute: RegimeRoute,
  RotationRoute: RotationRoute,
  SettingsRoute: SettingsRoute,
  TechnicalRoute: TechnicalRoute,
  ApiKlinesRoute: ApiKlinesRoute,
  TokenSymbolRoute: TokenSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
